# -*- coding: utf-8 -*-
"""Renomear Nome e Extensão.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qVtHvRjjbyUDiTdYcuQm7EdI8JYXeIgt
"""

import string
import os

diretorio = "/content/drive/Othercomputers/Meu computador/Data_set_Frutas/validation/apple"
i = 1

# Modifica nome
if os.path.isdir(diretorio) and not os.path.islink(diretorio):
    arquivos = os.listdir(diretorio)
    for arquivo in arquivos:
        parteQueSai = arquivo
        parteQueSubstitui = "Apple_" + str(i) + ".jpg"
        novoNome = str.replace(arquivo, parteQueSai, parteQueSubstitui)
        fullpathOld = os.path.join(diretorio,arquivo)
        fullpathNew = os.path.join(diretorio,novoNome)
        os.rename(fullpathOld, fullpathNew)
        i = i + 1
        print(i)