# -*- coding: utf-8 -*-
"""TCC.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qrDI33BiIS-lwx0oshoBNTXn85XcK1nJ

IMPORTAR BLIBLIOTECAS
"""

import cv2 as cv
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import os
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import accuracy_score
import csv

"""CODIFICAÇÃO"""

#PASSAR POR CADA IMAGEM

diretorio = "/content/drive/Othercomputers/Meu computador/Data_set_Frutas/dados/"

arquivos = os.listdir(diretorio) #Gerar uma lista aleatoria
arquivos.sort() #Ordenar a lista

#Função de tratamento de imagem-----------------------------------------------------
def imagem(nome_imagem, diretorio):
  img = cv.imread('/content/drive/Othercomputers/Meu computador/Data_set_Frutas/dados/' + diretorio + '/' + nome_imagem)
  img = cv.cvtColor(img, cv.COLOR_BGR2RGB)

  #Deixar a imagem mais lisa para remover detalhes das frutas -->MANTER ESSE BLUR
  img3 = cv.medianBlur(img, 13)
  
  #Remover pequenos ruídos da imagem
  kernel = np.ones((3,3),np.uint8)
  img2 = cv.medianBlur(img, 13)
  img4 = cv.morphologyEx(img2,cv.MORPH_CLOSE, kernel, iterations=4)
  
  #Tornar a imagem preto e branco para obter o contorno dela mais facil
  #img = cv.cvtColor(img,cv.COLOR_BGR2GRAY)
  #th, img = cv.threshold(img,80,255,cv.THRESH_BINARY_INV)
  #TA FUNCIONANDO
  
  plt.figure(figsize=(15,15))
  plt.subplot(141), plt.imshow(img), plt.axis('off')
  plt.subplot(142), plt.imshow(img4), plt.axis('off'), plt.title('Operação + Blur')
  plt.subplot(143), plt.imshow(img3), plt.axis('off'), plt.title('Blur solo')
  plt.show()

#Abrir o arquivo---------------------------------------------------
with open('/content/drive/Othercomputers/Meu computador/Data_set_Frutas/finformation.csv', 'w') as f:

  #Create the csv writer
  writer = csv.writer(f)
  writer2 = csv.DictWriter(f, fieldnames=['#','Classificacao']) #Titulos

  #Escrever cabeçalho
  writer2.writeheader()

  #Estrutura de repitição-----------------------------------------
  for arquivo in arquivos:

    #Rodar as pastas com cada imagem
    
    if arquivo == 'apple':
      arquivos = os.listdir(diretorio + 'apple')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Maca'])
        imagem(arquivo, 'apple')
        
    if arquivo == 'banana':
      arquivos = os.listdir(diretorio + 'banana')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Banana'])
        #imagem(arquivo, 'banana')

    if arquivo == 'grapes':
      arquivos = os.listdir(diretorio + 'grapes')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Uva'])
        #imagem(arquivo, 'grapes')

    if arquivo == 'kiwi':
      arquivos = os.listdir(diretorio + 'kiwi')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Kiwi']) 
        #imagem(arquivo)

    if arquivo == 'lemon':
      arquivos = os.listdir(diretorio + 'lemon')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Limao'])  
        #imagem(arquivo)

    if arquivo == 'mango':
      arquivos = os.listdir(diretorio + 'mango')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Manga'])
        #imagem(arquivo)

    if arquivo == 'orange':
      arquivos = os.listdir(diretorio + 'orange')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Laranja'])
        #imagem(arquivo)

    if arquivo == 'pear':
      arquivos = os.listdir(diretorio + 'pear')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Pera'])
        #imagem(arquivo)

    if arquivo == 'pineapple':
      arquivos = os.listdir(diretorio + 'pineapple')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Abacaxi'])
        #imagem(arquivo)   

    if arquivo == 'pomegranate':
      arquivos = os.listdir(diretorio + 'pomegranate')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Roma'])
        #imagem(arquivo) 

    if arquivo == 'tomato':
      arquivos = os.listdir(diretorio + 'tomato')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Tomate'])
        #imagem(arquivo)

    if arquivo == 'watermelon':
      arquivos = os.listdir(diretorio + 'watermelon')
      for arquivo in arquivos:
        writer.writerow([arquivo] + ['Melancia'])
        #imagem(arquivo)